### ISSUE TITLE
Annotation Time

### ISSUE THREAD

**Issue by kun-dragon** [BasitAlawode/Best_of_N_Trackers#1]
Great job! A Simple idea with wonderful results. How do you annotate all training videos by using 17 trackers? And how much time it will take?

**Comment by BasitAlawode** [comment]
I am assuming by annotation, you mean data generation for our BofN predictor. If yes, we run all trackers on the training videos to obtain their respective performance and then select the tracker with the best performance. This gives a video-'best tracker' pair. More details can be found in our paper.

Regarding the time, it depends on your computing resources.

**Comment by kun-dragon** [comment]
In your paper, the Bofn predictor is used to choose the best of 17 trackers. However, the workload of obtaining the AUC of all trackers for each training video is enormous.  Can you share information about your computing resources and the time cost for annotating all training videos?

**Comment by BasitAlawode** [comment]
At the moment, I cannot ascertain our actual time cost for annotating all the videos but one can easily determine the time it'll take a tracker to run a video, hence, the overall time on a dataset can easily be determined. As with most data creation tasks, running all the trackers on all the datasets will definitely take some time. However, this is a one-time task.
